
CREATE TABLE SRC_TBL
(
	SRC_ID int NOT NULL AUTO_INCREMENT,
	RESULT_ID int NOT NULL,
	FILE_NAME varchar(300) NOT NULL,
	SRC varchar(10000) NOT NULL,
	PRIMARY KEY (SRC_ID)
);

CREATE INDEX IDX_SRC_TBL ON SRC_TBL (RESULT_ID ASC, FILE_NAME ASC);

INSERT INTO SRC_TBL (RESULT_ID,FILE_NAME,SRC) select RESULT_ID,'answer.java',ANSWER as SRC FROM result_tbl WHERE ANSWER is not null;