package jp.ac.asojuku.asolearning.entity;

import java.io.Serializable;

/**
 * アバターマスタ モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class AvatarMasterEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** アバターID. */
	private Integer avatarId;

	/** アバターの種類. */
	private Integer kind;

	/** 解答数の条件（簡単）. */
	private Integer ansCondEasy;

	/** 解答数の条件（通常）. */
	private Integer ansCondNormal;

	/** 解答数の条件（難しい）. */
	private Integer ansCondHard;

	/** 点数条件（簡単）. */
	private Integer totalCndEasy;

	/** 点数条件（ふつう）. */
	private Integer totalCndNormal;

	/** 点数条件（難しい）. */
	private Integer totalCndHard;

	/** ファイル名. */
	private String fileName;

	/**
	 * コンストラクタ.
	 */
	public AvatarMasterEntity() {
	}

	/**
	 * アバターID を設定します.
	 * 
	 * @param avatarId
	 *            アバターID
	 */
	public void setAvatarId(Integer avatarId) {
		this.avatarId = avatarId;
	}

	/**
	 * アバターID を取得します.
	 * 
	 * @return アバターID
	 */
	public Integer getAvatarId() {
		return this.avatarId;
	}

	/**
	 * アバターの種類 を設定します.
	 * 
	 * @param kind
	 *            アバターの種類
	 */
	public void setKind(Integer kind) {
		this.kind = kind;
	}

	/**
	 * アバターの種類 を取得します.
	 * 
	 * @return アバターの種類
	 */
	public Integer getKind() {
		return this.kind;
	}

	/**
	 * 解答数の条件（簡単） を設定します.
	 * 
	 * @param ansCondEasy
	 *            解答数の条件（簡単）
	 */
	public void setAnsCondEasy(Integer ansCondEasy) {
		this.ansCondEasy = ansCondEasy;
	}

	/**
	 * 解答数の条件（簡単） を取得します.
	 * 
	 * @return 解答数の条件（簡単）
	 */
	public Integer getAnsCondEasy() {
		return this.ansCondEasy;
	}

	/**
	 * 解答数の条件（通常） を設定します.
	 * 
	 * @param ansCondNormal
	 *            解答数の条件（通常）
	 */
	public void setAnsCondNormal(Integer ansCondNormal) {
		this.ansCondNormal = ansCondNormal;
	}

	/**
	 * 解答数の条件（通常） を取得します.
	 * 
	 * @return 解答数の条件（通常）
	 */
	public Integer getAnsCondNormal() {
		return this.ansCondNormal;
	}

	/**
	 * 解答数の条件（難しい） を設定します.
	 * 
	 * @param ansCondHard
	 *            解答数の条件（難しい）
	 */
	public void setAnsCondHard(Integer ansCondHard) {
		this.ansCondHard = ansCondHard;
	}

	/**
	 * 解答数の条件（難しい） を取得します.
	 * 
	 * @return 解答数の条件（難しい）
	 */
	public Integer getAnsCondHard() {
		return this.ansCondHard;
	}

	/**
	 * 点数条件（簡単） を設定します.
	 * 
	 * @param totalCndEasy
	 *            点数条件（簡単）
	 */
	public void setTotalCndEasy(Integer totalCndEasy) {
		this.totalCndEasy = totalCndEasy;
	}

	/**
	 * 点数条件（簡単） を取得します.
	 * 
	 * @return 点数条件（簡単）
	 */
	public Integer getTotalCndEasy() {
		return this.totalCndEasy;
	}

	/**
	 * 点数条件（ふつう） を設定します.
	 * 
	 * @param totalCndNormal
	 *            点数条件（ふつう）
	 */
	public void setTotalCndNormal(Integer totalCndNormal) {
		this.totalCndNormal = totalCndNormal;
	}

	/**
	 * 点数条件（ふつう） を取得します.
	 * 
	 * @return 点数条件（ふつう）
	 */
	public Integer getTotalCndNormal() {
		return this.totalCndNormal;
	}

	/**
	 * 点数条件（難しい） を設定します.
	 * 
	 * @param totalCndHard
	 *            点数条件（難しい）
	 */
	public void setTotalCndHard(Integer totalCndHard) {
		this.totalCndHard = totalCndHard;
	}

	/**
	 * 点数条件（難しい） を取得します.
	 * 
	 * @return 点数条件（難しい）
	 */
	public Integer getTotalCndHard() {
		return this.totalCndHard;
	}

	/**
	 * ファイル名 を設定します.
	 * 
	 * @param fileName
	 *            ファイル名
	 */
	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	/**
	 * ファイル名 を取得します.
	 * 
	 * @return ファイル名
	 */
	public String getFileName() {
		return this.fileName;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((avatarId == null) ? 0 : avatarId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		AvatarMasterEntity other = (AvatarMasterEntity) obj;
		if (avatarId == null) {
			if (other.avatarId != null) {
				return false;
			}
		} else if (!avatarId.equals(other.avatarId)) {
			return false;
		}
		return true;
	}

}
