package jp.ac.asojuku.asolearning.entity;

import java.io.Serializable;

/**
 * 特徴テーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class CharactorEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 性格ID. */
	private Integer charactorId;

	/** ユーザーテーブル. */
	private UserTblEntity userTbl;

	/** 特徴マスタ. */
	private CharactorMasterEntity charactorMaster;

	/** 値. */
	private Integer value;

	/**
	 * コンストラクタ.
	 */
	public CharactorEntity() {
	}

	/**
	 * 性格ID を設定します.
	 * 
	 * @param charactorId
	 *            性格ID
	 */
	public void setCharactorId(Integer charactorId) {
		this.charactorId = charactorId;
	}

	/**
	 * 性格ID を取得します.
	 * 
	 * @return 性格ID
	 */
	public Integer getCharactorId() {
		return this.charactorId;
	}

	/**
	 * ユーザーテーブル を設定します.
	 * 
	 * @param userTbl
	 *            ユーザーテーブル
	 */
	public void setUserTbl(UserTblEntity userTbl) {
		this.userTbl = userTbl;
	}

	/**
	 * ユーザーテーブル を取得します.
	 * 
	 * @return ユーザーテーブル
	 */
	public UserTblEntity getUserTbl() {
		return this.userTbl;
	}

	/**
	 * 特徴マスタ を設定します.
	 * 
	 * @param charactorMaster
	 *            特徴マスタ
	 */
	public void setCharactorMaster(CharactorMasterEntity charactorMaster) {
		this.charactorMaster = charactorMaster;
	}

	/**
	 * 特徴マスタ を取得します.
	 * 
	 * @return 特徴マスタ
	 */
	public CharactorMasterEntity getCharactorMaster() {
		return this.charactorMaster;
	}

	/**
	 * 値 を設定します.
	 * 
	 * @param value
	 *            値
	 */
	public void setValue(Integer value) {
		this.value = value;
	}

	/**
	 * 値 を取得します.
	 * 
	 * @return 値
	 */
	public Integer getValue() {
		return this.value;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((charactorId == null) ? 0 : charactorId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		CharactorEntity other = (CharactorEntity) obj;
		if (charactorId == null) {
			if (other.charactorId != null) {
				return false;
			}
		} else if (!charactorId.equals(other.charactorId)) {
			return false;
		}
		return true;
	}

}
