package jp.ac.asojuku.asolearning.entity;

import java.io.Serializable;
import java.util.LinkedHashSet;
import java.util.Set;

/**
 * 学科マスター モデルクラス.
 *
 * @author generated by ERMaster
 * @version $Id$
 */
public class CourseMasterEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** COURSE_ID. */
	private Integer courseId;

	/** COURSE_NAME. */
	private String courseName;

	/** 課題公開テーブル 一覧. */
	private Set<TaskPublicTblEntity> taskPublicTblSet;

	/** ユーザーテーブル 一覧. */
	private Set<UserTblEntity> userTblSet;

	/**
	 * コンストラクタ.
	 */
	public CourseMasterEntity() {
		this.taskPublicTblSet = new LinkedHashSet<TaskPublicTblEntity>();
		this.userTblSet = new LinkedHashSet<UserTblEntity>();
	}

	/**
	 * COURSE_ID を設定します.
	 *
	 * @param courseId
	 *            COURSE_ID
	 */
	public void setCourseId(Integer courseId) {
		this.courseId = courseId;
	}

	/**
	 * COURSE_ID を取得します.
	 *
	 * @return COURSE_ID
	 */
	public Integer getCourseId() {
		return this.courseId;
	}

	/**
	 * COURSE_NAME を設定します.
	 *
	 * @param courseName
	 *            COURSE_NAME
	 */
	public void setCourseName(String courseName) {
		this.courseName = courseName;
	}

	/**
	 * COURSE_NAME を取得します.
	 *
	 * @return COURSE_NAME
	 */
	public String getCourseName() {
		return this.courseName;
	}

	/**
	 * 課題公開テーブル 一覧を設定します.
	 *
	 * @param taskPublicTblSet
	 *            課題公開テーブル 一覧
	 */
	public void setTaskPublicTblSet(Set<TaskPublicTblEntity> taskPublicTblSet) {
		this.taskPublicTblSet = taskPublicTblSet;
	}

	/**
	 * 課題公開テーブル を追加します.
	 *
	 * @param taskPublicTbl
	 *            課題公開テーブル
	 */
	public void addTaskPublicTbl(TaskPublicTblEntity taskPublicTbl) {
		this.taskPublicTblSet.add(taskPublicTbl);
	}

	/**
	 * 課題公開テーブル 一覧を取得します.
	 *
	 * @return 課題公開テーブル 一覧
	 */
	public Set<TaskPublicTblEntity> getTaskPublicTblSet() {
		return this.taskPublicTblSet;
	}

	/**
	 * ユーザーテーブル 一覧を設定します.
	 *
	 * @param userTblSet
	 *            ユーザーテーブル 一覧
	 */
	public void setUserTblSet(Set<UserTblEntity> userTblSet) {
		this.userTblSet = userTblSet;
	}

	/**
	 * ユーザーテーブル を追加します.
	 *
	 * @param userTbl
	 *            ユーザーテーブル
	 */
	public void addUserTbl(UserTblEntity userTbl) {
		this.userTblSet.add(userTbl);
	}

	/**
	 * ユーザーテーブル 一覧を取得します.
	 *
	 * @return ユーザーテーブル 一覧
	 */
	public Set<UserTblEntity> getUserTblSet() {
		return this.userTblSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((courseId == null) ? 0 : courseId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		CourseMasterEntity other = (CourseMasterEntity) obj;
		if (courseId == null) {
			if (other.courseId != null) {
				return false;
			}
		} else if (!courseId.equals(other.courseId)) {
			return false;
		}
		return true;
	}

}
