package jp.ac.asojuku.asolearning.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * 情報テーブル モデルクラス.
 *
 * @author generated by ERMaster
 * @version $Id$
 */
public class InfomationTblEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** INFOMATION_ID. */
	private Integer infomationId;

	/** タイトル. */
	private String title;

	/** メッセージ. */
	private String message;

	/** 登録日時. */
	private Date entryDate;

	/** 更新日時. */
	private Date updateDate;

	/** 作成者. */
	private Integer authorUserId;
	private UserTblEntity userEntity;

	/** お知らせ公開テーブル 一覧. */
	private Set<InfoPublicTblEntity> infoPublicTblSet;

	/**
	 * コンストラクタ.
	 */
	public InfomationTblEntity() {
		this.infoPublicTblSet = new HashSet<InfoPublicTblEntity>();
	}

	/**
	 * INFOMATION_ID を設定します.
	 *
	 * @param infomationId
	 *            INFOMATION_ID
	 */
	public void setInfomationId(Integer infomationId) {
		this.infomationId = infomationId;
	}

	/**
	 * INFOMATION_ID を取得します.
	 *
	 * @return INFOMATION_ID
	 */
	public Integer getInfomationId() {
		return this.infomationId;
	}

	/**
	 * タイトル を設定します.
	 *
	 * @param title
	 *            タイトル
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * タイトル を取得します.
	 *
	 * @return タイトル
	 */
	public String getTitle() {
		return this.title;
	}

	/**
	 * メッセージ を設定します.
	 *
	 * @param message
	 *            メッセージ
	 */
	public void setMessage(String message) {
		this.message = message;
	}

	/**
	 * メッセージ を取得します.
	 *
	 * @return メッセージ
	 */
	public String getMessage() {
		return this.message;
	}

	/**
	 * 登録日時 を設定します.
	 *
	 * @param entryDate
	 *            登録日時
	 */
	public void setEntryDate(Date entryDate) {
		this.entryDate = entryDate;
	}

	/**
	 * 登録日時 を取得します.
	 *
	 * @return 登録日時
	 */
	public Date getEntryDate() {
		return this.entryDate;
	}

	/**
	 * 更新日時 を設定します.
	 *
	 * @param updateDate
	 *            更新日時
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * 更新日時 を取得します.
	 *
	 * @return 更新日時
	 */
	public Date getUpdateDate() {
		return this.updateDate;
	}

	/**
	 * 作成者 を設定します.
	 *
	 * @param authorUserId
	 *            作成者
	 */
	public void setAuthorUserId(Integer authorUserId) {
		this.authorUserId = authorUserId;
	}

	/**
	 * 作成者 を取得します.
	 *
	 * @return 作成者
	 */
	public Integer getAuthorUserId() {
		return this.authorUserId;
	}

	/**
	 * お知らせ公開テーブル 一覧を設定します.
	 *
	 * @param infoPublicTblSet
	 *            お知らせ公開テーブル 一覧
	 */
	public void setInfoPublicTblSet(Set<InfoPublicTblEntity> infoPublicTblSet) {
		this.infoPublicTblSet = infoPublicTblSet;
	}

	/**
	 * お知らせ公開テーブル を追加します.
	 *
	 * @param infoPublicTbl
	 *            お知らせ公開テーブル
	 */
	public void addInfoPublicTbl(InfoPublicTblEntity infoPublicTbl) {
		this.infoPublicTblSet.add(infoPublicTbl);
	}

	/**
	 * お知らせ公開テーブル 一覧を取得します.
	 *
	 * @return お知らせ公開テーブル 一覧
	 */
	public Set<InfoPublicTblEntity> getInfoPublicTblSet() {
		return this.infoPublicTblSet;
	}

	/**
	 * @return userEntity
	 */
	public UserTblEntity getUserEntity() {
		return userEntity;
	}

	/**
	 * @param userEntity セットする userEntity
	 */
	public void setUserEntity(UserTblEntity userEntity) {
		this.userEntity = userEntity;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((infomationId == null) ? 0 : infomationId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		InfomationTblEntity other = (InfomationTblEntity) obj;
		if (infomationId == null) {
			if (other.infomationId != null) {
				return false;
			}
		} else if (!infomationId.equals(other.infomationId)) {
			return false;
		}
		return true;
	}

}
