package jp.ac.asojuku.asolearning.entity;

import java.io.Serializable;

/**
 * 結果詳細テーブル（テストケース） モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ResultTestcaseTblEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 結果テーブル. */
	private ResultTblEntity resultTbl;

	/** テストケースID. */
	private Integer testcaseId;

	/** 得点. */
	private Integer score;

	/** メッセージ. */
	private String message;

	/**
	 * コンストラクタ.
	 */
	public ResultTestcaseTblEntity() {
	}

	/**
	 * 結果テーブル を設定します.
	 * 
	 * @param resultTbl
	 *            結果テーブル
	 */
	public void setResultTbl(ResultTblEntity resultTbl) {
		this.resultTbl = resultTbl;
	}

	/**
	 * 結果テーブル を取得します.
	 * 
	 * @return 結果テーブル
	 */
	public ResultTblEntity getResultTbl() {
		return this.resultTbl;
	}

	/**
	 * テストケースID を設定します.
	 * 
	 * @param testcaseId
	 *            テストケースID
	 */
	public void setTestcaseId(Integer testcaseId) {
		this.testcaseId = testcaseId;
	}

	/**
	 * テストケースID を取得します.
	 * 
	 * @return テストケースID
	 */
	public Integer getTestcaseId() {
		return this.testcaseId;
	}

	/**
	 * 得点 を設定します.
	 * 
	 * @param score
	 *            得点
	 */
	public void setScore(Integer score) {
		this.score = score;
	}

	/**
	 * 得点 を取得します.
	 * 
	 * @return 得点
	 */
	public Integer getScore() {
		return this.score;
	}

	/**
	 * メッセージ を設定します.
	 * 
	 * @param message
	 *            メッセージ
	 */
	public void setMessage(String message) {
		this.message = message;
	}

	/**
	 * メッセージ を取得します.
	 * 
	 * @return メッセージ
	 */
	public String getMessage() {
		return this.message;
	}


}
