package jp.ac.asojuku.asolearning.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * 課題グループテーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class TaskGroupTblEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** TASK_GROUP_ID. */
	private Integer taskGroupId;

	/** TASK_GROUP_NAME. */
	private String taskGroupName;

	/** ENTRY_DATE. */
	private Date entryDate;

	/** UPDATE_DATE. */
	private Date updateDate;

	/** 課題テーブル 一覧. */
	private Set<TaskTblEntity> taskTblSet;

	/**
	 * コンストラクタ.
	 */
	public TaskGroupTblEntity() {
		this.taskTblSet = new HashSet<TaskTblEntity>();
	}

	/**
	 * TASK_GROUP_ID を設定します.
	 * 
	 * @param taskGroupId
	 *            TASK_GROUP_ID
	 */
	public void setTaskGroupId(Integer taskGroupId) {
		this.taskGroupId = taskGroupId;
	}

	/**
	 * TASK_GROUP_ID を取得します.
	 * 
	 * @return TASK_GROUP_ID
	 */
	public Integer getTaskGroupId() {
		return this.taskGroupId;
	}

	/**
	 * TASK_GROUP_NAME を設定します.
	 * 
	 * @param taskGroupName
	 *            TASK_GROUP_NAME
	 */
	public void setTaskGroupName(String taskGroupName) {
		this.taskGroupName = taskGroupName;
	}

	/**
	 * TASK_GROUP_NAME を取得します.
	 * 
	 * @return TASK_GROUP_NAME
	 */
	public String getTaskGroupName() {
		return this.taskGroupName;
	}

	/**
	 * ENTRY_DATE を設定します.
	 * 
	 * @param entryDate
	 *            ENTRY_DATE
	 */
	public void setEntryDate(Date entryDate) {
		this.entryDate = entryDate;
	}

	/**
	 * ENTRY_DATE を取得します.
	 * 
	 * @return ENTRY_DATE
	 */
	public Date getEntryDate() {
		return this.entryDate;
	}

	/**
	 * UPDATE_DATE を設定します.
	 * 
	 * @param updateDate
	 *            UPDATE_DATE
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * UPDATE_DATE を取得します.
	 * 
	 * @return UPDATE_DATE
	 */
	public Date getUpdateDate() {
		return this.updateDate;
	}

	/**
	 * 課題テーブル 一覧を設定します.
	 * 
	 * @param taskTblSet
	 *            課題テーブル 一覧
	 */
	public void setTaskTblSet(Set<TaskTblEntity> taskTblSet) {
		this.taskTblSet = taskTblSet;
	}

	/**
	 * 課題テーブル を追加します.
	 * 
	 * @param taskTbl
	 *            課題テーブル
	 */
	public void addTaskTbl(TaskTblEntity taskTbl) {
		this.taskTblSet.add(taskTbl);
	}

	/**
	 * 課題テーブル 一覧を取得します.
	 * 
	 * @return 課題テーブル 一覧
	 */
	public Set<TaskTblEntity> getTaskTblSet() {
		return this.taskTblSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((taskGroupId == null) ? 0 : taskGroupId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		TaskGroupTblEntity other = (TaskGroupTblEntity) obj;
		if (taskGroupId == null) {
			if (other.taskGroupId != null) {
				return false;
			}
		} else if (!taskGroupId.equals(other.taskGroupId)) {
			return false;
		}
		return true;
	}

}
