package jp.ac.asojuku.asolearning.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * 課題公開テーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class TaskPublicTblEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 課題テーブル. */
	private TaskTblEntity taskTbl;

	/** 学科マスター. */
	private CourseMasterEntity courseMaster;

	/** 公開状態ID. */
	private PublicStatusMasterEntity publicStatusMaster;

	/** PUBLIC_DATETIME. */
	private Date publicDatetime;

	/** 締切日. */
	private Date endDatetime;

	/**
	 * コンストラクタ.
	 */
	public TaskPublicTblEntity() {
	}

	/**
	 * 課題テーブル を設定します.
	 * 
	 * @param taskTbl
	 *            課題テーブル
	 */
	public void setTaskTbl(TaskTblEntity taskTbl) {
		this.taskTbl = taskTbl;
	}

	/**
	 * 課題テーブル を取得します.
	 * 
	 * @return 課題テーブル
	 */
	public TaskTblEntity getTaskTbl() {
		return this.taskTbl;
	}

	/**
	 * 学科マスター を設定します.
	 * 
	 * @param courseMaster
	 *            学科マスター
	 */
	public void setCourseMaster(CourseMasterEntity courseMaster) {
		this.courseMaster = courseMaster;
	}

	/**
	 * 学科マスター を取得します.
	 * 
	 * @return 学科マスター
	 */
	public CourseMasterEntity getCourseMaster() {
		return this.courseMaster;
	}

	/**
	 * 公開状態ID を設定します.
	 * 
	 * @param publicStatusMaster
	 *            公開状態ID
	 */
	public void setPublicStatusMaster(PublicStatusMasterEntity publicStatusMaster) {
		this.publicStatusMaster = publicStatusMaster;
	}

	/**
	 * 公開状態ID を取得します.
	 * 
	 * @return 公開状態ID
	 */
	public PublicStatusMasterEntity getPublicStatusMaster() {
		return this.publicStatusMaster;
	}

	/**
	 * PUBLIC_DATETIME を設定します.
	 * 
	 * @param publicDatetime
	 *            PUBLIC_DATETIME
	 */
	public void setPublicDatetime(Date publicDatetime) {
		this.publicDatetime = publicDatetime;
	}

	/**
	 * PUBLIC_DATETIME を取得します.
	 * 
	 * @return PUBLIC_DATETIME
	 */
	public Date getPublicDatetime() {
		return this.publicDatetime;
	}

	/**
	 * 締切日 を設定します.
	 * 
	 * @param endDatetime
	 *            締切日
	 */
	public void setEndDatetime(Date endDatetime) {
		this.endDatetime = endDatetime;
	}

	/**
	 * 締切日 を取得します.
	 * 
	 * @return 締切日
	 */
	public Date getEndDatetime() {
		return this.endDatetime;
	}


}
