INSERT INTO COURSE_MASTER(COURSE_ID,COURSE_NAME)VALUES(28,"情報システム科 Aクラス");
INSERT INTO COURSE_MASTER(COURSE_ID,COURSE_NAME)VALUES(29,"情報システム専攻科 Bクラス");
INSERT INTO COURSE_MASTER(COURSE_ID,COURSE_NAME)VALUES(30,"情報システム専攻科 Cクラス");
INSERT INTO COURSE_MASTER(COURSE_ID,COURSE_NAME)VALUES(31,"情シ 情シ専 情工 Dクラス");
INSERT INTO COURSE_MASTER(COURSE_ID,COURSE_NAME)VALUES(32,"情シ 情シ専 Eクラス");
INSERT INTO COURSE_MASTER(COURSE_ID,COURSE_NAME)VALUES(33,"情報工学科 Fクラス");