package jp.ac.asojuku.asolearning.entity;

import java.io.Serializable;

/**
 * ソースコードテーブル モデルクラス.
 *
 * @author generated by ERMaster
 * @version $Id$
 */
public class SrcTblEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** SRC_ID. */
	private Integer srcId;

	/** 結果テーブル. */
	private ResultTblEntity resultTbl;
	private Integer resultId;

	/** ファイル名. */
	private String fileName;

	/** ソースコード. */
	private String src;

	/**
	 * コンストラクタ.
	 */
	public SrcTblEntity() {
	}

	/**
	 * SRC_ID を設定します.
	 *
	 * @param srcId
	 *            SRC_ID
	 */
	public void setSrcId(Integer srcId) {
		this.srcId = srcId;
	}

	/**
	 * SRC_ID を取得します.
	 *
	 * @return SRC_ID
	 */
	public Integer getSrcId() {
		return this.srcId;
	}

	/**
	 * 結果テーブル を設定します.
	 *
	 * @param resultTbl
	 *            結果テーブル
	 */
	public void setResultTbl(ResultTblEntity resultTbl) {
		this.resultTbl = resultTbl;
	}

	/**
	 * 結果テーブル を取得します.
	 *
	 * @return 結果テーブル
	 */
	public ResultTblEntity getResultTbl() {
		return this.resultTbl;
	}

	/**
	 * ファイル名 を設定します.
	 *
	 * @param fileName
	 *            ファイル名
	 */
	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	/**
	 * ファイル名 を取得します.
	 *
	 * @return ファイル名
	 */
	public String getFileName() {
		return this.fileName;
	}

	/**
	 * ソースコード を設定します.
	 *
	 * @param src
	 *            ソースコード
	 */
	public void setSrc(String src) {
		this.src = src;
	}

	/**
	 * ソースコード を取得します.
	 *
	 * @return ソースコード
	 */
	public String getSrc() {
		return this.src;
	}

	/**
	 * @return resultId
	 */
	public Integer getResultId() {
		return resultId;
	}

	/**
	 * @param resultId セットする resultId
	 */
	public void setResultId(Integer resultId) {
		this.resultId = resultId;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((srcId == null) ? 0 : srcId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		SrcTblEntity other = (SrcTblEntity) obj;
		if (srcId == null) {
			if (other.srcId != null) {
				return false;
			}
		} else if (!srcId.equals(other.srcId)) {
			return false;
		}
		return true;
	}

}
