package jp.ac.asojuku.asolearning.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * 課題公開テーブル モデルクラス.
 *
 * @author generated by ERMaster
 * @version $Id$
 */
public class TaskPublicTblEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 課題テーブル. */
	private TaskTblEntity taskTbl;

	/** 学科マスター. */
	private CourseMasterEntity courseMaster;

	/** 公開状態ID. */
	private PublicStatusMasterEntity publicStatusMaster;

	/** PUBLIC_DATETIME. */
	private Date publicDatetime;

	/** 公開終了日. */
	private Date endDatetime;

	/** GRADE1. */
	private Integer grade1;

	/** GRADE2. */
	private Integer grade2;

	/** GRADE3. */
	private Integer grade3;

	/** GRADE4. */
	private Integer grade4;

	/**
	 * コンストラクタ.
	 */
	public TaskPublicTblEntity() {
	}

	/**
	 * 課題テーブル を設定します.
	 *
	 * @param taskTbl
	 *            課題テーブル
	 */
	public void setTaskTbl(TaskTblEntity taskTbl) {
		this.taskTbl = taskTbl;
	}

	/**
	 * 課題テーブル を取得します.
	 *
	 * @return 課題テーブル
	 */
	public TaskTblEntity getTaskTbl() {
		return this.taskTbl;
	}

	/**
	 * 学科マスター を設定します.
	 *
	 * @param courseMaster
	 *            学科マスター
	 */
	public void setCourseMaster(CourseMasterEntity courseMaster) {
		this.courseMaster = courseMaster;
	}

	/**
	 * 学科マスター を取得します.
	 *
	 * @return 学科マスター
	 */
	public CourseMasterEntity getCourseMaster() {
		return this.courseMaster;
	}

	/**
	 * 公開状態ID を設定します.
	 *
	 * @param publicStatusMaster
	 *            公開状態ID
	 */
	public void setPublicStatusMaster(PublicStatusMasterEntity publicStatusMaster) {
		this.publicStatusMaster = publicStatusMaster;
	}

	/**
	 * 公開状態ID を取得します.
	 *
	 * @return 公開状態ID
	 */
	public PublicStatusMasterEntity getPublicStatusMaster() {
		return this.publicStatusMaster;
	}

	/**
	 * PUBLIC_DATETIME を設定します.
	 *
	 * @param publicDatetime
	 *            PUBLIC_DATETIME
	 */
	public void setPublicDatetime(Date publicDatetime) {
		this.publicDatetime = publicDatetime;
	}

	/**
	 * PUBLIC_DATETIME を取得します.
	 *
	 * @return PUBLIC_DATETIME
	 */
	public Date getPublicDatetime() {
		return this.publicDatetime;
	}

	/**
	 * 公開終了日 を設定します.
	 *
	 * @param endDatetime
	 *            公開終了日
	 */
	public void setEndDatetime(Date endDatetime) {
		this.endDatetime = endDatetime;
	}

	/**
	 * 公開終了日 を取得します.
	 *
	 * @return 公開終了日
	 */
	public Date getEndDatetime() {
		return this.endDatetime;
	}

	/**
	 * GRADE1 を設定します.
	 *
	 * @param grade1
	 *            GRADE1
	 */
	public void setGrade1(Integer grade1) {
		this.grade1 = grade1;
	}

	/**
	 * GRADE1 を取得します.
	 *
	 * @return GRADE1
	 */
	public Integer getGrade1() {
		return this.grade1;
	}

	/**
	 * GRADE2 を設定します.
	 *
	 * @param grade2
	 *            GRADE2
	 */
	public void setGrade2(Integer grade2) {
		this.grade2 = grade2;
	}

	/**
	 * GRADE2 を取得します.
	 *
	 * @return GRADE2
	 */
	public Integer getGrade2() {
		return this.grade2;
	}

	/**
	 * GRADE3 を設定します.
	 *
	 * @param grade3
	 *            GRADE3
	 */
	public void setGrade3(Integer grade3) {
		this.grade3 = grade3;
	}

	/**
	 * GRADE3 を取得します.
	 *
	 * @return GRADE3
	 */
	public Integer getGrade3() {
		return this.grade3;
	}

	/**
	 * GRADE4 を設定します.
	 *
	 * @param grade4
	 *            GRADE4
	 */
	public void setGrade4(Integer grade4) {
		this.grade4 = grade4;
	}

	/**
	 * GRADE4 を取得します.
	 *
	 * @return GRADE4
	 */
	public Integer getGrade4() {
		return this.grade4;
	}


}
