
DROP INDEX IDX_TP_TBL_COURSE_ID ON INFO_PUBLIC_TBL;
DROP INDEX IDX_TP_TBL_TASKID_COURSEID ON INFO_PUBLIC_TBL;

DROP TABLE IF EXISTS INFO_PUBLIC_TBL;
DROP TABLE IF EXISTS INFOMATION_TBL;


CREATE TABLE INFOMATION_TBL
(
	INFOMATION_ID int NOT NULL AUTO_INCREMENT,
	TITLE varchar(200) NOT NULL,
	MESSAGE varchar(300) NOT NULL,
	ENTRY_DATE timestamp NOT NULL,
	UPDATE_DATE timestamp NOT NULL,
	AUTHOR_USER_ID int NOT NULL,
	PRIMARY KEY (INFOMATION_ID)
);


CREATE TABLE INFO_PUBLIC_TBL
(
	INFOMATION_ID int NOT NULL,
	-- 公開/非公開の対象ID
	COURSE_ID int NOT NULL COMMENT '公開/非公開の対象ID',
	-- 0:非公開
	-- 1:公開
	STATUS_ID int NOT NULL COMMENT '0:非公開
1:公開',
	-- 公開開始の日時
	PUBLIC_DATETIME datetime COMMENT '公開開始の日時',
	-- NULLの場合は期限なし
	END_DATETIME datetime COMMENT 'NULLの場合は期限なし'
) COMMENT = '課題公開設定テーブル';


ALTER TABLE INFO_PUBLIC_TBL
	ADD FOREIGN KEY (INFOMATION_ID)
	REFERENCES INFOMATION_TBL (INFOMATION_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE INFO_PUBLIC_TBL
	ADD FOREIGN KEY (COURSE_ID)
	REFERENCES COURSE_MASTER (COURSE_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

CREATE INDEX IDX_TP_TBL_COURSE_ID ON INFO_PUBLIC_TBL ();
CREATE INDEX IDX_TP_TBL_TASKID_COURSEID ON INFO_PUBLIC_TBL ();
CREATE INDEX IDX_INFO_AUTHORID ON INFOMATION_TBL (AUTHOR_USER_ID ASC);
