CREATE INDEX IDX_HIS_USER_ID ON HISTORY_TBL (USER_ID ASC);
CREATE INDEX IDX_HIS_ACTION_ID ON HISTORY_TBL (ACTION_ID ASC);
CREATE INDEX IDX_HIS_ACTION_DATE ON HISTORY_TBL (ACTION_DATE ASC);
CREATE INDEX IDX_USER_GRADE ON USER_TBL (GRADE ASC);
CREATE INDEX IDX_USER_MAILADRESS ON USER_TBL (MAILADRESS ASC);