ALTER TABLE TASK_PUBLIC_TBL ADD GRADE1 int DEFAULT 0 ;
ALTER TABLE TASK_PUBLIC_TBL ADD GRADE2 int DEFAULT 0 ;
ALTER TABLE TASK_PUBLIC_TBL ADD GRADE3 int DEFAULT 0 ;
ALTER TABLE TASK_PUBLIC_TBL ADD GRADE4 int DEFAULT 0 ;