/**
 *
 */
package jp.ac.asojuku.asolearning.err;

/**
 * エラーコード
 * @author nishino
 *
 */
public enum ErrorCode {

	SUCCESS("0000") ,
	//ログイン(00xx)
	ERR_LOGIN("0001"),
	//会員登録(01xx)
	ERR_MEMBER_ENTRY_MAILADDRESS("0101"),
	ERR_MEMBER_ENTRY_NAME("0102"),
	ERR_MEMBER_ENTRY_ADDRESS("0103"),
	ERR_MEMBER_ENTRY_TELNUMBER("0104"),
	ERR_MEMBER_ENTRY_MAILADDRESS_ISNEED("0105"),
	ERR_MEMBER_ENTRY_NAME_ISNEED("0106"),
	ERR_MEMBER_ENTRY_ADDRESS_ISNEED("0107"),
	ERR_MEMBER_ENTRY_TELNUMBER_ISNEED("0108"),
	ERR_MEMBER_ENTRY_PASSWORD_NOTMATCH("0109"),
	ERR_MEMBER_ENTRY_PASSWORD_LENGTH("0110"),
	ERR_MEMBER_ENTRY_DUPLICATE_MEIL("0111"),
	//課題関連(02xx)
	ERR_TASK_EXT_ERROR("0201"),
	ERR_TASK_ID_ERROR("0202"),
	ERR_TASK_NAME_EMPTY("0203"),
	ERR_TASK_NAME_LENGTH("0204"),
	ERR_TASK_Q_EMPTY("0205"),
	ERR_TASK_Q_LENGTH("0206"),
	ERR_TASK_PDATE_ERR("0207"),
	ERR_TASK_EDATE_ERR("0208"),
	ERR_TASK_INPUTF_ERR("0209"),
	ERR_TASK_OUTPUTF_ERR("0210"),
	ERR_TASK_ALLMOST_ERR("0211"),
	ERR_TASK_DUPLICATE_ERR("0212"),

	//その他のエラー
	ERR_SESSION_INVLIDATE("9901"),
	ERR_SYSTEM_ERROR("9999"),
	;

	private String code;

	private ErrorCode(String code){ this.code = code; }

	public String getCode(){ return code; }

}
