package jp.ac.asojuku.asolearning.entity;

import java.io.Serializable;

/**
 * アバターマスタ モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class AvatarMasterEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** アバターID. */
	private Integer avatarId;

	/** アバターの種類. */
	private Integer kind;

	/** 解答数の条件. */
	private Integer ansCond;

	/** 点数条件. */
	private Integer totalCnd;

	/** ファイル名. */
	private String fileName;

	/** ユーザーテーブル. */
	private UserTblEntity userTbl;

	/**
	 * コンストラクタ.
	 */
	public AvatarMasterEntity() {
	}

	/**
	 * アバターID を設定します.
	 * 
	 * @param avatarId
	 *            アバターID
	 */
	public void setAvatarId(Integer avatarId) {
		this.avatarId = avatarId;
	}

	/**
	 * アバターID を取得します.
	 * 
	 * @return アバターID
	 */
	public Integer getAvatarId() {
		return this.avatarId;
	}

	/**
	 * アバターの種類 を設定します.
	 * 
	 * @param kind
	 *            アバターの種類
	 */
	public void setKind(Integer kind) {
		this.kind = kind;
	}

	/**
	 * アバターの種類 を取得します.
	 * 
	 * @return アバターの種類
	 */
	public Integer getKind() {
		return this.kind;
	}

	/**
	 * 解答数の条件 を設定します.
	 * 
	 * @param ansCond
	 *            解答数の条件
	 */
	public void setAnsCond(Integer ansCond) {
		this.ansCond = ansCond;
	}

	/**
	 * 解答数の条件 を取得します.
	 * 
	 * @return 解答数の条件
	 */
	public Integer getAnsCond() {
		return this.ansCond;
	}

	/**
	 * 点数条件 を設定します.
	 * 
	 * @param totalCnd
	 *            点数条件
	 */
	public void setTotalCnd(Integer totalCnd) {
		this.totalCnd = totalCnd;
	}

	/**
	 * 点数条件 を取得します.
	 * 
	 * @return 点数条件
	 */
	public Integer getTotalCnd() {
		return this.totalCnd;
	}

	/**
	 * ファイル名 を設定します.
	 * 
	 * @param fileName
	 *            ファイル名
	 */
	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	/**
	 * ファイル名 を取得します.
	 * 
	 * @return ファイル名
	 */
	public String getFileName() {
		return this.fileName;
	}

	/**
	 * ユーザーテーブル を設定します.
	 * 
	 * @param userTbl
	 *            ユーザーテーブル
	 */
	public void setUserTbl(UserTblEntity userTbl) {
		this.userTbl = userTbl;
	}

	/**
	 * ユーザーテーブル を取得します.
	 * 
	 * @return ユーザーテーブル
	 */
	public UserTblEntity getUserTbl() {
		return this.userTbl;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((avatarId == null) ? 0 : avatarId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		AvatarMasterEntity other = (AvatarMasterEntity) obj;
		if (avatarId == null) {
			if (other.avatarId != null) {
				return false;
			}
		} else if (!avatarId.equals(other.avatarId)) {
			return false;
		}
		return true;
	}

}
