package jp.ac.asojuku.asolearning.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * 履歴テーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class HistoryTblEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ユーザーテーブル. */
	private UserTblEntity userTbl;

	/** 動作マスター. */
	private ActionMasterEntity actionMaster;

	/** ACTION_DATE. */
	private Date actionDate;

	/**
	 * コンストラクタ.
	 */
	public HistoryTblEntity() {
	}

	/**
	 * ユーザーテーブル を設定します.
	 * 
	 * @param userTbl
	 *            ユーザーテーブル
	 */
	public void setUserTbl(UserTblEntity userTbl) {
		this.userTbl = userTbl;
	}

	/**
	 * ユーザーテーブル を取得します.
	 * 
	 * @return ユーザーテーブル
	 */
	public UserTblEntity getUserTbl() {
		return this.userTbl;
	}

	/**
	 * 動作マスター を設定します.
	 * 
	 * @param actionMaster
	 *            動作マスター
	 */
	public void setActionMaster(ActionMasterEntity actionMaster) {
		this.actionMaster = actionMaster;
	}

	/**
	 * 動作マスター を取得します.
	 * 
	 * @return 動作マスター
	 */
	public ActionMasterEntity getActionMaster() {
		return this.actionMaster;
	}

	/**
	 * ACTION_DATE を設定します.
	 * 
	 * @param actionDate
	 *            ACTION_DATE
	 */
	public void setActionDate(Date actionDate) {
		this.actionDate = actionDate;
	}

	/**
	 * ACTION_DATE を取得します.
	 * 
	 * @return ACTION_DATE
	 */
	public Date getActionDate() {
		return this.actionDate;
	}


}
