package jp.ac.asojuku.asolearning.entity;

import java.io.Serializable;
import java.util.LinkedHashSet;
import java.util.Set;

/**
 * 公開状態ID モデルクラス.
 *
 * @author generated by ERMaster
 * @version $Id$
 */
public class PublicStatusMasterEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 状態ID. */
	private Integer statusId;

	/** 状態名. */
	private String statusName;

	/** 課題公開テーブル 一覧. */
	private Set<TaskPublicTblEntity> taskPublicTblSet;

	/**
	 * コンストラクタ.
	 */
	public PublicStatusMasterEntity() {
		this.taskPublicTblSet = new LinkedHashSet<TaskPublicTblEntity>();
	}

	/**
	 * 状態ID を設定します.
	 *
	 * @param statusId
	 *            状態ID
	 */
	public void setStatusId(Integer statusId) {
		this.statusId = statusId;
	}

	/**
	 * 状態ID を取得します.
	 *
	 * @return 状態ID
	 */
	public Integer getStatusId() {
		return this.statusId;
	}

	/**
	 * 状態名 を設定します.
	 *
	 * @param statusName
	 *            状態名
	 */
	public void setStatusName(String statusName) {
		this.statusName = statusName;
	}

	/**
	 * 状態名 を取得します.
	 *
	 * @return 状態名
	 */
	public String getStatusName() {
		return this.statusName;
	}

	/**
	 * 課題公開テーブル 一覧を設定します.
	 *
	 * @param taskPublicTblSet
	 *            課題公開テーブル 一覧
	 */
	public void setTaskPublicTblSet(Set<TaskPublicTblEntity> taskPublicTblSet) {
		this.taskPublicTblSet = taskPublicTblSet;
	}

	/**
	 * 課題公開テーブル を追加します.
	 *
	 * @param taskPublicTbl
	 *            課題公開テーブル
	 */
	public void addTaskPublicTbl(TaskPublicTblEntity taskPublicTbl) {
		this.taskPublicTblSet.add(taskPublicTbl);
	}

	/**
	 * 課題公開テーブル 一覧を取得します.
	 *
	 * @return 課題公開テーブル 一覧
	 */
	public Set<TaskPublicTblEntity> getTaskPublicTblSet() {
		return this.taskPublicTblSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((statusId == null) ? 0 : statusId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		PublicStatusMasterEntity other = (PublicStatusMasterEntity) obj;
		if (statusId == null) {
			if (other.statusId != null) {
				return false;
			}
		} else if (!statusId.equals(other.statusId)) {
			return false;
		}
		return true;
	}

}
